version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "angularjs",
    "ember",
    "react",
    "vue",
    "meteor",
    "angular"
  ]

[[analyzers]]
name = "ruby"
enabled = true